### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by ghost** [codingsmartschool/gocurl#3]
The error is on : 
- Line 19
- Line 25

Command Line : 

``` shell
$ go run setup.go
# command-line-arguments
./setup.go:19: undefined: log.Error
./setup.go:25: undefined: log.Error
```

**Comment by vck** [comment]
this issue has been fixed on this commit https://github.com/codingsmartschool/gocurl/commit/ff15e099a23d4896e7be591e4c85e89c5716b1b0 @christoga
