### ISSUE TITLE
Curl feature

### ISSUE THREAD

**Issue by ghost** [codingsmartschool/gocurl#5]
After reading https://en.wikipedia.org/wiki/CURL
I think gocurl should add new feature as curl command line tool has a lot of them

Anyone agree?
cc @vickydasta @widnyana

**Comment by widnyana** [comment]
@christoga did you mean you want to port curl [source code](https://github.com/bagder/curl) to golang?

---

edit:

also, please take a look here https://mholt.github.io/curl-to-go/ and here https://github.com/search?utf8=%E2%9C%93&q=curl+golang&type=Repositories&ref=searchresults

**Comment by ghost** [comment]
No, I mean gocurl should be a tool to use curl in golang

**Comment by widnyana** [comment]
here you go then https://github.com/andelf/go-curl
